edit pipeline ecr step

diff --git a/.github/workflows/deploy_infrastructure_ecr_lambda.yaml b/.github/workflows/deploy_infrastructure_ecr_lambda.yaml
--- a/.github/workflows/deploy_infrastructure_ecr_lambda.yaml
+++ b/.github/workflows/deploy_infrastructure_ecr_lambda.yaml
@@ -61,20 +61,20 @@ jobs:
 
       - name: Build and push lambda image
         run: |
-        LAMBDA_TAG=${{ inputs.lambda_version }}
-            
-        aws ecr describe-images --repository-name=$ECR_REPO_LAMBDA --image-ids=imageTag=$LAMBDA_TAG 2>/dev/null
+          LAMBDA_TAG=${{ inputs.lambda_version }}
+              
+          aws ecr describe-images --repository-name=$ECR_REPO_LAMBDA --image-ids=imageTag=$LAMBDA_TAG 2>/dev/null
 
-        if [[ $? == 0 ]]; then
-            echo "Image already exists. Skipping build and push."
-        else
-            echo "Image not found. Building and pushing..."
-            docker build -t $ECR_REPO_LAMBDA:$LAMBDA_TAG app
-            docker tag $ECR_REPO_LAMBDA:$LAMBDA_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
-            docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
-        fi
-            
-        echo "LAMBDA_IMAGE=${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG" >> $GITHUB_ENV
+          if [[ $? == 0 ]]; then
+              echo "Image already exists. Skipping build and push."
+          else
+              echo "Image not found. Building and pushing..."
+              docker build -t $ECR_REPO_LAMBDA:$LAMBDA_TAG app
+              docker tag $ECR_REPO_LAMBDA:$LAMBDA_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
+              docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
+          fi
+              
+          echo "LAMBDA_IMAGE=${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG" >> $GITHUB_ENV
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
