lambda built with docker

diff --git a/.github/workflows/deploy_infrastructure_ecr_lambda.yaml b/.github/workflows/deploy_infrastructure_ecr_lambda.yaml
--- a/.github/workflows/deploy_infrastructure_ecr_lambda.yaml
+++ b/.github/workflows/deploy_infrastructure_ecr_lambda.yaml
@@ -62,9 +62,22 @@ jobs:
       - name: Build and push lambda image
         run: |
           LAMBDA_TAG=${{ inputs.lambda_version }}
-          docker build -t $ECR_REPO_LAMBDA:$LAMBDA_TAG app
-          docker tag $ECR_REPO_LAMBDA:$LAMBDA_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
-          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
+          IMAGE_EXISTS=$(aws ecr describe-images \
+            --repository-name $ECR_REPO_LAMBDA \
+            --image-ids imageTag=$LAMBDA_TAG \
+            --query 'imageDetails[0].imageTags[0]' \
+            --output text 2>/dev/null || echo "NONE")
+
+
+          if [ "$IMAGE_EXISTS" = "NONE" ]; then
+            echo "Image not found. Building and pushing..."
+            docker build -t $ECR_REPO_LAMBDA:$LAMBDA_TAG app
+            docker tag $ECR_REPO_LAMBDA:$LAMBDA_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
+            docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG
+          else
+            echo "Image already exists. Skipping build and push."
+          fi
+
           echo "LAMBDA_IMAGE=${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_LAMBDA}:$LAMBDA_TAG" >> $GITHUB_ENV
 
       - name: Setup Terraform
@@ -85,9 +98,8 @@ jobs:
           terraform plan \
             -var="region=${AWS_REGION}" \
             -var="project_name=${TF_PROJECT_NAME}" \
-            -var="lambda_version=${{ inputs.lambda_version }}" \
             -var="environment=${{ inputs.environment }}" \
-            -var="ecr_repo_lambda=${ECR_REPO_LAMBDA}"
+            -var="lambda_image=${LAMBDA_IMAGE}"
 
       - name: Terraform Apply
         working-directory: terraform-infrastructure
@@ -95,9 +107,8 @@ jobs:
           terraform apply -auto-approve \
             -var="region=${AWS_REGION}" \
             -var="project_name=${TF_PROJECT_NAME}" \
-            -var="lambda_version=${{ inputs.lambda_version }}" \
             -var="environment=${{ inputs.environment }}" \
-            -var="ecr_repo_lambda=${ECR_REPO_LAMBDA}"
+            -var="lambda_image=${LAMBDA_IMAGE}"
 
       - name: Get Terraform Outputs
         uses: actions/upload-artifact@v4
